/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xxx_media_dbl_Media */

#ifndef _Included_com_xxx_media_dbl_Media
#define _Included_com_xxx_media_dbl_Media
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xxx_media_dbl_Media
 * Method:    playPCM
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xxx_media_dbl_Media_playPCM
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_xxx_media_dbl_Media
 * Method:    startRecord
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xxx_media_dbl_Media_startRecord
  (JNIEnv *, jclass);

/*
 * Class:     com_xxx_media_dbl_Media
 * Method:    stopRecord
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xxx_media_dbl_Media_stopRecord
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
